### ISSUE TITLE
Hit

### ISSUE THREAD

**Issue by devetude** [Hitit-Dev/Hitit-API#4]
1. 인덱스 부분에서 Long(class) 사용한 것을 long(primitive) 자료형으로 변경해주세요.
2. tidx는 timeline idx를 의미합니다. 따라서 Timeline 객체로 연결해주세요.
3. lombok 적용해주세요.
4. indent 맞춰주세요.

@sjaqjwor 부탁드려요.

**Comment by sjaqjwor** [comment]
적용 완료
